### ISSUE TITLE
Support "external" RightScripts in ServerTemplate YAML

### ISSUE THREAD

**Issue by douglaswth** [rightscale/right_st#16]
Currently, the RightScripts specification in right_st's ServerTemplate YAML only supports RightScripts that are uploaded from the same location as the YAML file; however, you may wish to include "external" RightScripts such as from the MultiCloud Marketplace or just an HREF of a RightScript in your account.

Here are some samples of how this could look:

```yaml
RightScripts:
  Boot:
  - path/to/script.sh
  - Name: Really Cool External Script from MultiCloud Marketplace
    Revision: 42
  - Href: /api/right_scripts/123456789
```
