### ISSUE TITLE
Validation Fails

### ISSUE THREAD

**Issue by loopbackv6** [rightscale/right_st#17]
Unable to validate ServerTemaplate:
```
$ right_st st upload generic-foundation-image.yaml:
Validating generic-foundation-image.yaml
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x277bb]

goroutine 1 [running]:
panic(0x80e340, 0xc8200100d0)
	/Users/travis/.gimme/versions/go1.6.darwin.amd64/src/runtime/panic.go:464 +0x3e6
main.validateServerTemplate(0x7fff5fbff573, 0x1d, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/rightscale/right_st/servertemplate.go:586 +0x14eb
main.stUpload(0xc820282710, 0x1, 0x1, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/rightscale/right_st/servertemplate.go:44 +0x1df
main.main()
	/Users/travis/gopath/src/github.com/rightscale/right_st/main.go:131 +0xc07
```

This is an approximation of generic-foundation-image.yaml:
```
Name: st-austin-generic-foundation-image
Description: Testing Right ST
Inputs:
  HOST: "blank"
RightScripts:
  Boot:
  - ../right_scripts/foo.sh
  - ../right_scripts/bar.sh
  - ../right_scripts/foo_bar.sh
  Operational:
  Decommission:
MultiCloudImages:
- Name: mci-generic-foundation-image-master
  Revision: 0
- Href: ...
```
